Added t_create-required-traits
ENG517/Topic-Model-3 pull request #13
Opened 2024-10-30 20:46 UTC by jckinsey01

Added t_create-required-traits. I added "selecting farm type" task to the end of the "selecting required traits" task.

Let me know what you think. I am thinking that for alerts we can have different types of alerts, such as FYI (for non-urgent information), Tip (for tips not made readily known in the game), and Warning (for potential hazards).

2024-11-05 19:50 UTC, lily-soetebier requested changes
I left a few in line comments, but there were just a few things to be tweaked! Mostly, which is my fault for not explaining, the only aspects of the character creation process that have defaults are the physical attributes (i.e. sex, hair style, shirt, etc.) so it may be best to tweak the info to inform the user that what is shown in the images has been added by us as demonstration.

2024-11-05 19:50 UTC, lily-soetebier commented on creating-a-new-save-procedure/creating-a-new-save-tasks/t_create-required-traits.dita
> +    <cmd>Launch Stardew Valley, and click New on the top-left corner. You will be brought to the character and farm creation page.</cmd>
There is a solid possibility that i put top left in my original procedure, but its actually in the bottom left of the screen

2024-11-05 19:50 UTC, lily-soetebier commented on creating-a-new-save-procedure/creating-a-new-save-tasks/t_create-required-traits.dita
> +    <info>FYI: Daisy Day is the default character name.</info>
There also isn't a default name, it starts blank. Those were names/items I added to the procedure just to show the fields being filled in

2024-11-05 19:50 UTC, lily-soetebier commented on creating-a-new-save-procedure/creating-a-new-save-tasks/t_create-required-traits.dita
> +    <info>FYI: Daisy Day is the default character name.</info>
I think that you can easily leave this in, especially if we start integrating images at some point because it will be useful to give context as to why the fields are filled in, but the ones on the screen the user is seeing aren't

2024-11-06 00:59 UTC, jckinsey01 commented on creating-a-new-save-procedure/creating-a-new-save-tasks/t_create-required-traits.dita
> +    <info>FYI: Daisy Day is the default character name.</info>
All fixed!

2024-11-06 01:15 UTC, lily-soetebier approved these changes
Looks good!

2024-11-06 01:15 UTC, merged