Created C_intro_to_farming
ENG517/Topic-Model-3 pull request #25
Opened 2024-11-08 02:01 UTC by jckinsey01

Created the concept topic for the intro to farming. Let me know if this is all good!

2024-11-08 02:22 UTC, lily-soetebier requested changes
I made a few inline comments about things that have changed since moving from the og markdown to this version of events!

2024-11-08 02:22 UTC, lily-soetebier commented on farming-spring-crops-procedure/farming-spring-crops-concepts/c_intro_to_farming.dita
> +     There are some pre-requisited to have squared away before starting your new save.
Instead of saying new save here, i think it might be more helpful to say "before you start farming" or something to that effect

2024-11-08 02:22 UTC, lily-soetebier commented on farming-spring-crops-procedure/farming-spring-crops-concepts/c_intro_to_farming.dita
> +    Once all of the pre-requisites to starting the game have been completed, there are some in-game requirements and items needed to begin farming.
One thing that changed in translating this from markdown to dita is that the expansion of the preparing land task meant that more tools were technically required as pre-req (pickaxe, axe, and the scythe was made necessary rather than optional). Also the section that talked about sprinklers and fertilizer (per dr. lindgren's initial comments to me when he graded the other project) was cut, so we can remove that from the list.

if we want i can add a concept about them if we want but honestly it doesn't really feel needed for the scope of the project to me.

2024-11-08 16:54 UTC, lily-soetebier commented on farming-spring-crops-procedure/farming-spring-crops-concepts/c_intro_to_farming.dita
> +    Once all of the pre-requisites to starting the game have been completed, there are some in-game requirements and items needed to begin farming.
Update on this: I ended up adding conditional notes to the planting seeds, and maintaining crop tasks respectively regarding the sprinklers and fertilizers so now they will only show up in "expert" versions. This will be on the PR I'm going to push soon with the DITAVAl files and a start on the attributes

2024-11-09 15:49 UTC, jckinsey01 commented on farming-spring-crops-procedure/farming-spring-crops-concepts/c_intro_to_farming.dita
> +    Once all of the pre-requisites to starting the game have been completed, there are some in-game requirements and items needed to begin farming.
Alright, I added the pickaxe, axe, and the scythe to the required in game pre-reqs and added "before you begin farming" instead of "before you begin your new save"

2024-11-09 15:50 UTC, jckinsey01 commented
I'm going to re-request  review so you can make sure it looks good w those changes, idk if you'll get a notification just from my comments.

2024-11-11 01:31 UTC, lily-soetebier reviewed
Looks great! Going to merge it now!

2024-11-11 01:32 UTC, lily-soetebier approved these changes

2024-11-11 01:32 UTC, merged